Repository CosmosOS/Cosmos, pull requests merged in 2021-06, with the labels that each got.

#1818 [Installer] Update UI
  source/Cosmos.Build.Builder/App.xaml
  source/Cosmos.Build.Builder/App.xaml.cs
  source/Cosmos.Build.Builder/BuildTasks/ProcessBuildTaskBase.cs
  source/Cosmos.Build.Builder/Cosmos.Build.Builder.csproj
  source/Cosmos.Build.Builder/CosmosBuildDefinition.cs
  source/Cosmos.Build.Builder/Dependencies/InnoSetupDependency.cs
  source/Cosmos.Build.Builder/Dependencies/ProperRepoNameDependency.cs
  source/Cosmos.Build.Builder/Dependencies/ReposDependency.cs
  source/Cosmos.Build.Builder/Dependencies/VisualStudioDependency.cs
  source/Cosmos.Build.Builder/Dependencies/VisualStudioWorkloadsDependency.cs
  source/Cosmos.Build.Builder/ViewModels/DependencyInstallationDialogViewModel.cs
  source/Cosmos.Build.Builder/ViewModels/MainWindowViewModel.cs
  source/Cosmos.Build.Builder/Views/DependencyInstallationDialog.xaml
  source/Cosmos.Build.Builder/Views/MainWindow.xaml
  source/Cosmos.Build.Builder/Views/MessageBox.xaml
  source/Cosmos.Build.Builder/Views/MessageBox.xaml.cs
  source/Cosmos.Build.Builder/Views/VisualStudioInstanceDialog.xaml
Labels: Area: Installer

#1799 FTP Server Implementation + TCB Implementation
  Docs/articles/Kernel/Network.md
  source/Cosmos.System2/Network/IPv4/TCP/FTP/FtpClient.cs
  source/Cosmos.System2/Network/IPv4/TCP/FTP/FtpCommandManager.cs
  source/Cosmos.System2/Network/IPv4/TCP/FTP/FtpServer.cs
  source/Cosmos.System2/Network/IPv4/TCP/TCPClient.cs
  source/Cosmos.System2/Network/IPv4/TCP/TCPPacket.cs
  source/Cosmos.System2/Network/IPv4/TCP/Tcp.cs
  source/Cosmos.System2/Network/IPv4/TCP/TcpListener.cs
Labels: Area: Networking

#1832 Implement FAT32 formatting
  Tests/Cosmos.System.Tests/VFSManagerTest.cs
  Tests/Kernels/Cosmos.Kernel.Tests.DiskManager/System.FileSystem/DiskManagerTest.cs
  source/Cosmos.Core/ManagedMemoryBlock.cs
  source/Cosmos.HAL2/BlockDevice/BlockDevice.cs
  source/Cosmos.System2/FileSystem/CosmosVFS.cs
  source/Cosmos.System2/FileSystem/DiskManager.cs
  source/Cosmos.System2/FileSystem/FAT/FatFileSystem.cs
Labels: Area: File System
